### ISSUE TITLE
AirPlay Icon on Top Left of the Application

### ISSUE THREAD

**Issue by Mattefarax** [hirbod/react-native-volume-manager#10]
Hello,
when I execute the function setVolume on iOS, in the Top Left of my application show up an AirPlay Icon white that i can't remove. What can i do to fix this problem?
![GitHub Issue](https://user-images.githubusercontent.com/84333770/225643022-a5056040-03a1-41d6-8ace-338f3f1e0cf4.jpeg)

**Comment by hirbod** [comment]
That is very weird. Which iOS Version?

**Comment by Mattefarax** [comment]
15.7 and 16.2

**Comment by Sewb21** [comment]
I also have noticed this too

**Comment by Sewb21** [comment]
@hirbod I added a potential fix on my local project which seemed to work but I've been unable to test the example project on a device due to signing issues and I don't think this issue appears on the sim.

An initial fix I tried was explicitly hiding the route button (https://developer.apple.com/documentation/mediaplayer/mpvolumeview/1620075-showsroutebutton) but that method is deprecated it hid the AirPlay icon but seemed to show another random circle icon (image attached). I could hide this with `showsVolumeSlider` but this broke the `showNativeUI` functionality.

The fix that seems to work fine is adding `volumeView.transform = CGAffineTransformMakeScale(0.1, 0.1);`, after the view is initialized, to scale down the icons. I think it would just need testing on the example app on a real device to make sure it works as expected but not too sure how to deal with the signing error.

```
No profiles for 'com.hirbod.rnvme' were found. Xcode couldn't find any iOS App Development provisioning profiles matching 'com.hirbod.rnvme'.
```

![IMG_1663](https://user-images.githubusercontent.com/61282033/226567224-d142e0ae-6d50-4897-8074-cab9a9e117bf.jpg)

**Comment by hirbod** [comment]
@Sewb21 you'll need to open the example in XCode and change that value. I'll optimize the example soon.
I'll have a look at the issue this weekend.

**Comment by hirbod** [comment]
I have found a proper fix for this. Will release in an hour

**Comment by hirbod** [comment]
Version 1.3.0 has been released. This issue is resolved now.
